server:
  cors:
    allow_origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
      - "http://172.19.0.1:3000"
      - "http://172.19.0.1:8080"
    allow_credentials: true
    allow_methods: ["GET", "POST", "PATCH", "DELETE", "OPTIONS"]
    allow_headers:
      [
        "Origin",
        "Content-Length",
        "Content-Type",
        "Content-Language",
        "Accept",
        "Accept-Language",
        "User-Agent",
      ]
    max_age: 12h
